/*
*
* Copyright 2015 IK4-Tekniker All Rights Reserved
*
* This file is part of Health Questionnaire SE at FISTAR https://www.fi-star.eu/  
*
* Health Questionnaire SE is free software: you can redistribute it and/or
* modify it under the terms of the GNU Affero General Public License as
* published by the Free Software Foundation, either version 3 of the
* License, or (at your option) any later version.
*
* Health Questionnaire SE is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero
* General Public License for more details.
*
* You should have received a copy of the GNU Affero General Public License
* along with Health Questionnaire SE. If not, see http://www.gnu.org/licenses/.
*
* For those usages not covered by this license please contact with
* patricia.casla at tekniker dot es
*
* Author: Ignacio Lazaro Llorente
*/
package es.tekniker.framework.ktek.exception;

public class KtekExceptionCode {
	
	public static int EXCEPTION_CODE_ROLE_NO_VALID=1000;
	public static int EXCEPTION_CODE_ROLE_NO_DATA_DEFINED_FOR_ROLE=1001;
		
	public static int EXCEPTION_CODE_LOGIN_REQUIRED_DATA_NO_DEFINED=1002;
	public static int EXCEPTION_CODE_LOGIN_NO_DATA_DEFINED_FOR_USER=1003;		
	public static int EXCEPTION_CODE_LOGIN_USERDATASESSION_CREATION_ERROR=1004;	
	public static int EXCEPTION_CODE_LOGIN_USER_DOES_NOT_EXIST=1005;
	public static int EXCEPTION_CODE_LOGIN_USER_NOT_ASSCOCIATED_TO_TELECAREPROGRAM=1006;	
	public static int EXCEPTION_CODE_LOGIN_TOKEN_EXPIRED=1007;
	public static int EXCEPTION_CODE_LOGIN_TOKEN_NOT_VALID=1008;	
	public static int EXCEPTION_CODE_LOGIN_SETTINGS_NOT_DEFINED=1009;
	public static int EXCEPTION_CODE_LOGIN_PASSWORD_NOT_RIGHT=1010;
		
	public static int EXCEPTION_CODE_LEARNING_LEARNINGSESSION_DOES_NOT_EXISTS=1011;	
	public static int EXCEPTION_CODE_LEARNING_LEARNINGMODULE_DOES_NOT_EXISTS=1012;
	public static int EXCEPTION_CODE_LEARNING_LEARNINGEXERCISE_DOES_NOT_EXISTS=1013;
	public static int EXCEPTION_CODE_LEARNING_LEARNINGRESULTEXERCISE_DOES_NOT_EXISTS=1014;	
	public static int EXCEPTION_CODE_LEARNING_USAGEPARAMETERTYPE_NOT_VALID=1015;
	
	public static int EXCEPTION_CODE_USER_PROGRAM_DOES_NOT_EXIST=1016;
	
	public static int EXCEPTION_AUTENTICATION_MODE_EXTERNAL_NOT_IMPLEMENTED=1017;
		
	public static int EXCEPTION_CODE_TOKEN_VALUE_NO_DEFINED=1018;
	public static int EXCEPTION_CODE_IDLANG_VALUE_NO_DEFINED=1019;
	
	public static int EXCEPTION_CODE_LEARNINGMODULE_VALUE_NO_DEFINED=1020;
	public static int EXCEPTION_CODE_LEARNINGSESSION_VALUE_NO_DEFINED=1021;
	public static int EXCEPTION_CODE_LEARNINGEXERCISE_VALUE_NO_DEFINED=1022;
	
	public static int EXCEPTION_CODE_USERPROGRAM_VALUE_NO_DEFINED=1023;
	
	public static int EXCEPTION_CODE_STATUS_VALUE_NO_DEFINED=1024;
	
	public static int EXCEPTION_CODE_LOGIN_USER_VALUE_NO_DEFINED=1025;
	
	public static int EXCEPTION_CODE_TELECARE_PROGRAM_DOES_NOT_EXIST=1026;
	public static int EXCEPTION_CODE_USER_EXT_DOES_NOT_EXIST=1027;
	
	public static int EXCEPTION_CODE_QUESTIONNAIRE_SECTION_DOES_NOT_EXIST=1028;
	public static int EXCEPTION_CODE_QUESTIONNAIRE_SECTION_NOT_ALL_DEFINED=1029;
	public static int EXCEPTION_CODE_QUESTIONNAIRE_SECTION_NOT_DEFINED=1030;	
	public static int EXCEPTION_CODE_QUESTIONNAIRE_ITEMS_DOES_NOT_EXIST=1031;	
	public static int EXCEPTION_CODE_QUESTIONNAIRE_ITEM_NOT_DEFINED=1032;	
	public static int EXCEPTION_CODE_QUESTIONNAIRE_QUESTION_DOES_NOT_EXISTS=1033;	
	public static int EXCEPTION_CODE_QUESTIONNAIRE_ANSWER_NOT_RIGHT=1034;
	public static int EXCEPTION_CODE_QUESTIONNAIRE_DOES_NOT_EXIST=1035;	
	public static int EXCEPTION_CODE_QUESTIONNAIRE_RESULT_INSERT_ERROR=1036;
	public static int EXCEPTION_CODE_QUESTIONNAIRE_ANSWER_DOES_NOT_EXIST=1037;
	
	public static int EXCEPTION_CODE_STATUS_LEARNING_UPDATE_ERROR=1038;	
	public static int EXCEPTION_CODE_STATUS_LEARNING_UPDATE_MAX_NUMBER_TRIALS=1039;

	public static int EXCEPTION_CODE_USER_DOES_NOT_EXIST = 1040;
	
	public static int EXCEPTION_CODE_USER_CREATE_ERROR = 1041;
	public static int EXCEPTION_CODE_USER_CREATE_DATA_REQUIRED_NOT_DEFINED = 1042;

	public static int EXCEPTION_CODE_USER_ERROR_DELETE_USER = 1043;
	public static int EXCEPTION_CODE_USER_ERROR_DELETE_USER_SESSION_DATA = 1044;
	
	public static int EXCEPTION_CODE_QUESTIONNAIRE_TYPE_NOT_ASSESSMENT = 1045;
	public static int EXCEPTION_CODE_QUESTIONNAIRE_TYPE_NOT_MONITORING = 1046;
	
	
	public static int EXCEPTION_CODE_QUESTIONNAIRE_PARAMETER_VALUE_NOT_VALID = 1047;	
	
	public static int EXCEPTION_CODE_QUESTIONNAIRE_MONITORING_SCHEDULE_DATA_NOT_DEFINED = 1048;
	public static int EXCEPTION_CODE_QUESTIONNAIRE_DATEVALIDTO_NOT_DEFINED = 1049;
	public static int EXCEPTION_CODE_QUESTIONNAIRE_DATEVALIDFROM_NOT_DEFINED = 1050;
	public static int EXCEPTION_CODE_QUESTIONNAIRE_PERIODICITYVALUE_NOT_DEFINED = 1051;
	
	public static int EXCEPTION_CODE_QUESTIONNAIRE_COMPLETIONINTERVALVALUE_NOT_DEFINED = 1052;

	public static int EXCEPTION_CODE_QUESTIONNAIRE_RESULT_DOES_NOT_EXIST = 1053;
	
	public static int EXCEPTION_CODE_IDUSER_VALUE_NO_DEFINED= 1054;
	
	public static int EXCEPTION_CODE_IDTELECAREPROGRAM_VALUE_NO_DEFINED= 1055;
	public static int EXCEPTION_CODE_IDPROFESSIONAL_VALUE_NO_DEFINED= 1056;
	public static int EXCEPTION_CODE_IDPATIENT_VALUE_NO_DEFINED= 1057;
	public static int EXCEPTION_CODE_IDUSERPROGRAM_VALUE_NO_DEFINED= 1058;
	
	public static int EXCEPTION_CODE_IDLEARNINGMODULE_VALUE_NO_DEFINED= 1059;
	public static int EXCEPTION_CODE_IDLEARNINGSESSION_VALUE_NO_DEFINED= 1060;
	public static int EXCEPTION_CODE_IDEXERCISE_VALUE_NO_DEFINED= 1061;
	public static int EXCEPTION_CODE_IDRESULTEXERCISE_VALUE_NO_DEFINED= 1062;
	public static int EXCEPTION_CODE_IDQUESTIONNAIRE_VALUE_NO_DEFINED= 1063;
		
	public static int EXCEPTION_CODE_DATEFROM_VALUE_NO_DEFINED= 1064;
	public static int EXCEPTION_CODE_DATETO_VALUE_NO_DEFINED= 1065;
	public static int EXCEPTION_CODE_ORDERBY_VALUE_NO_DEFINED= 1066;
	
	public static int EXCEPTION_CODE_COD_TELECAREPROGRAM_VALUE_NO_DEFINED= 1067;
	public static int EXCEPTION_CODE_COD_IDRESULTQUESTIONNAIRE_VALUE_NO_DEFINED= 1068;
		
	public static int EXCEPTION_CODE_STATUS_LEARNING_UPDATE_STATUS_NEXT_ERROR = 1069;
	public static int EXCEPTION_CODE_STATUS_EXERCISE_UPDATE_ERROR_FOR_LEARNING_SESSION = 1070;

	public static int EXCEPTION_CODE_QUESTIONNAIRE_CONFIGURATION_NOT_DEFINED = 1071;
	public static int EXCEPTION_CODE_QUESTIONNAIRE_CONFIGURATION_CONTEXT_BROKER_NOT_DEFINED = 1072;
	public static int EXCEPTION_CODE_QUESTIONNAIRE_CONFIGURATION_CONTEXT_BROKER_ENDPOINT_NOT_DEFINED = 1073;
	public static int EXCEPTION_CODE_QUESTIONNAIRE_CONFIGURATION_CONTEXT_BROKER_PORT_NOT_DEFINED = 1074;
	public static int EXCEPTION_CODE_QUESTIONNAIRE_CONFIGURATION_EVENT_SERVICE_NOT_DEFINED = 1075;
	public static int EXCEPTION_CODE_QUESTIONNAIRE_CONFIGURATION_EVENT_SERVICE_ENDPOINT_NOT_DEFINED = 1076;
	public static int EXCEPTION_CODE_QUESTIONNAIRE_CONFIGURATION_EVENT_SERVICE_TOKEN_NOT_DEFINED = 1077;
	
	public static int EXCEPTION_CODE_PERSISSTENT_EXCEPTION = 1078;
	
	public static int EXCEPTION_CODE_QUESTIONNAIRE_MONITORING_PLANNING_ALREADY_DONE = 1079;

	public static int EXCEPTION_CODE_QUESTIONNAIRE_MONITORING_PLANNING_NO_DEFINED = 1080;
	
}

